[versions]
agp = "8.6.1"
kotlin = "2.0.20"
material = "1.13.0-alpha06"
appcompat = "1.7.0"
coroutines = "1.9.0"
glide = "4.16.0"
lifecycle = "2.8.6"
core-ktx = "1.13.1"
fragment-ktx = "1.8.3"
splashscreen = "1.2.0-alpha02"
preference = "1.2.1"
datastore = "1.1.1"
serialization-json = "1.7.3"
okhttp-bom = "4.12.0"
desugar = "2.1.2"
compose-bom = "2024.09.02"
activity-compose = "1.9.2"
navigation-compose = "2.8.1"
material-motion = "2.0.1"
about-libraries = "11.2.3"
sora-editor = "0.23.4"
android-jvm = "17"
android-compileSdk = "35"
android-targetSdk = "35"
android-minSdk = "26"
antlr = "4.13.2"
libgdx = "1.12.1"

[plugins]
agp-lib = { id = "com.android.library", version.ref = "agp" }
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
about-libraries-plugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }

[libraries]
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
material-compose = { group = "androidx.compose.material", name = "material", version = "1.8.0-alpha02" }
material3-compose = { group = "androidx.compose.material3", name = "material3", version = "1.3.0" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
material-motion-compose-core = { group = "io.github.fornewid", name = "material-motion-compose-core", version.ref = "material-motion" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-json" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp-bom" }

gson = { group = "com.google.code.gson", name = "gson", version = "2.11.0" }

altlr = { group = "org.antlr", name = "antlr", version.ref = "antlr" }
antlr-runtime = { group = "org.antlr", name = "antlr-runtime", version.ref = "antlr" }

libgdx = { group = "com.badlogicgames.gdx", name = "gdx", version.ref = "libgdx" }
libgdx-backend-android = { group = "com.badlogicgames.gdx", name = "gdx-backend-android", version.ref = "libgdx" }

desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar" }

sora-editor = { group = "io.github.Rosemoe.sora-editor", name = "editor", version.ref = "sora-editor" }
sora-editor-lsp = { group = "io.github.Rosemoe.sora-editor", name = "editor-lsp", version.ref = "sora-editor" }
sora-editor-language-java = { group = "io.github.Rosemoe.sora-editor", name = "language-java", version.ref = "sora-editor" }
sora-editor-language-textmate = { group = "io.github.Rosemoe.sora-editor", name = "language-textmate", version.ref = "sora-editor" }