[versions]
agp = "8.6.0"
kotlin = "2.0.20"
compose = "2024.09.00"
aboutlibraries = "11.2.3"
material = "1.13.0-alpha05"
appcompat = "1.7.0"
kotlinCoroutines = "1.9.0-RC.2"
glide = "4.16.0"
okhttp = "4.12.0"
soraEditor = "0.23.4"
koin = "3.5.6"
desugar = "2.1.2"
activityCompose = "1.9.2"
navigationCompose = "2.8.0"
materialMotionCompose = "2.0.1"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-library = { id = "com.android.library", version.ref = "agp" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlinCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlinCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
soraEditor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "soraEditor" }
aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlibraries" }
aboutLibrariesCompose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }
aboutlibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koinCompose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
materialMotionCompose = { module = "io.github.fornewid:material-motion-compose-core", version.ref = "materialMotionCompose" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
compose = { module = "androidx.compose:compose-bom", version.ref = "compose" }
