name: Code Formatter

on: 
  workflow_dispatch:

jobs:
  format:
    name: Format Kotlin Code with ktfmt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
          
      - name: Download ktfmt
        run: |
          wget https://github.com/trindadedev13/ktfmt/releases/download/1.0.0/ktfmt-0.54-SNAPSHOT-jar-with-dependencies.jar -O ktfmt.jar

      - name: Run ktfmt on Kotlin files
        run: |
          find . -name "*.kt" -exec java -jar ktfmt.jar --google-style {} +

      - name: Commit and Push changes
        run: |
          git config --global user.name "trindadedev13"
          git config --global user.email "devsuay@gmail.com"
          git fetch origin ${GITHUB_REF_NAME}:temp
          git add .
          git commit -m "chore: Format Kotlin Code" -m "format code with ktfmt in github actions"
          git rebase temp
          git push origin HEAD:${GITHUB_REF_NAME}
        env:
          TOKEN: ${{ secrets.SUPER_TOKEN }}
        continue-on-error: true
  
  format-java:
    name: Format Java Code with Google Java Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
          
      - name: Download Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/download/v1.24.0/google-java-format-1.24.0-all-deps.jar -O google-java-format.jar

      - name: Run Google Java Format in Java files
        run: |
          find . -name "*.java" -exec java -jar google-java-format.jar --replace {} +

      - name: Commit and Push changes
        run: |
          git config --global user.name "trindadedev13"
          git config --global user.email "devsuay@gmail.com"
          git fetch origin ${GITHUB_REF_NAME}:temp
          git add .
          git commit -m "chore: Format Java Code" -m "format code with google java format in github actions"
          git rebase temp
          git push origin HEAD:${GITHUB_REF_NAME}
        env:
          TOKEN: ${{ secrets.SUPER_TOKEN }}
        continue-on-error: true
        
  format-xml:
    name: Format XML Code with xml-formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' 

      - name: Install xml-formatter
        run: |
          npm install -g xml-formatter

      - name: Run xml-formatter on XML files
        run: |
          find . -name "*.xml" -exec xml-formatter {} -o {} +

      - name: Commit and Push changes
        run: |
          git config --global user.name "trindadedev13"
          git config --global user.email "devsuay@gmail.com"
          git fetch origin ${GITHUB_REF_NAME}:temp
          git add .
          git commit -m "chore: Format XML Code" -m "format code with xml-formatter in github actions"
          git rebase temp
          git push origin HEAD:${GITHUB_REF_NAME}
        env:
          TOKEN: ${{ secrets.SUPER_TOKEN }}
        continue-on-error: true