name: Notify Telegram

on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - app/**
      - easy-ui/**
      - feature-compose/**
      - feature/**
      - gradle/**
      - images/**
      - robok/**
      - .gitignore
      - LICENSE
      - README.md
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - renovate.json
      - settings.gradle.kts
  pull_request:
    paths:
      - .github/**
      - app/**
      - easy-ui/**
      - feature-compose/**
      - feature/**
      - gradle/**
      - images/**
      - robok/**
      - .gitignore
      - LICENSE
      - README.md
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - renovate.json
      - settings.gradle.kts

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_RBKINC_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_RBKINC_CHAT_ID }}
          TELEGRAM_TOPIC_ID: 1100
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            commit_message=$(git log -1 --pretty=%B)
            commit_hash=$(git log -1 --pretty=%h)
            commit_author=$(git log -1 --pretty=%an)
            branch_name=$(git rev-parse --abbrev-ref HEAD)
            previous_commit_hash=$(git log -2 --pretty=%h | tail -n 1)
            repo_url="https://github.com/${{ github.repository }}"
            compare_url="${repo_url}/compare/${previous_commit_hash}...${commit_hash}"
            commit_url="${repo_url}/commit/${commit_hash}"
            message="🔨 [1 new commit](${compare_url}) to Robok-Engine:${branch_name}%0A%0A[${commit_hash}](${commit_url}): ${commit_message} by ${commit_author}"
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            pr_title="${{ github.event.pull_request.title }}"
            pr_number="${{ github.event.pull_request.number }}"
            pr_author="${{ github.event.pull_request.user.login }}"
            pr_url="${{ github.event.pull_request.html_url }}"
            message="🔍 [New Pull Request ${pr_number}](${pr_url}) to Robok-Engine:%0A%0A**Title:** \`${pr_title}\`%0A**Author:** \`${pr_author}\`%0A[View PR](${pr_url})"
          else
            echo "Unsupported event: ${{ github.event_name }}"
            exit 1
          fi

          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
            -d "chat_id=${TELEGRAM_CHAT_ID}" \
            -d "parse_mode=Markdown" \
            -d "text=${message}" \
            -d "message_thread_id=${TELEGRAM_TOPIC_ID}"
