name: Notify Telegram

on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - app/**
      - easy-ui/**
      - feature-compose/**
      - feature/**
      - gradle/**
      - images/**
      - robok/**
      - .gitignore
      - core/**
      - core-compose/**
      - app-strings/**
      - LICENSE
      - README.md
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - renovate.json
      - settings.gradle.kts
  pull_request:
    paths:
      - .github/**
      - app/**
      - easy-ui/**
      - feature-compose/**
      - feature/**
      - gradle/**
      - core/**
      - core-compose/**
      - app-strings/**
      - images/**
      - robok/**
      - .gitignore
      - LICENSE
      - README.md
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - renovate.json
      - settings.gradle.kts

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: notify telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: '${{ secrets.TELEGRAM_RBKINC_BOT_TOKEN }}'
          chat_id: '${{ secrets.TELEGRAM_RBKINC_CHAT_ID }}'
          topic_id: '${{ 1100 }}'